### PR TITLE
Fix null pointer exception when input value is null

### LINKED ISSUE #292: Empty input value causes null pointer exception
inputs:
  - input1:

### PR DESCRIPTION
**Pull request by oritstone**
Fixes #292

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/transformers/AbstractInputsTransformer.java [hunk 1]
```diff
@@ -32,7 +32,11 @@ protected Input transformSingleInput(Object rawInput) {
             return new Input(inputName, null);
         } else if (rawInput instanceof Map) {
             Map.Entry<String, ?> entry = ((Map<String, ?>) rawInput).entrySet().iterator().next();
-            if (entry.getValue() instanceof Map) {
+            Object entryValue = entry.getValue();
+            if(entryValue == null){
+                throw new RuntimeException("Could not transform Input : " + rawInput + " Since it has an null value");
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/transformers/AbstractInputsTransformer.java]: minor observation: typo? ->  **a** null value

**Comment by Bonczidai** [comment]
added my comment(s) - looks gr8 :+1:
