### PR TITLE
Parallel Loop doesn't work iterating through maps

### LINKED ISSUE #839: Parallel Loop doesn't work iterating through maps
Steps:
1. Add a Parallel Loop step in a flow, e.g.

parallel_loop:
  for: 'attempt,values in {1:1,2:2}'

and run it.

Expected result: The PL should iterate through the key:value pairs of the map

Actual result: Error 
"Flow finished with failure
Command failed java.lang.RuntimeException: Score Error Event:Error occurred duri
ng split step  , Failed to run the action! Wrong arguments were passed to class:
 io.cloudslang.lang.runtime.steps.ParallelLoopExecutionData, method: addBranches
, reason: argument type mismatch" (CS 9.70)

NOTE: Loop iterates fine through maps

### LINKED ISSUE #862: Parallel loop iterator string list
in parallel loop when using list of string as the iterator it does not work
in loop it works
example:

namespace: aaaaa
flow:
  name: fatherflow2
  workflow:
    - rrrr:
        parallel_loop:
          for: "k in **'1,2,3'**"
          do:
            aaaaa.rrrr: []
        navigate:
          - FAILURE: on_failure
          - SUCCESS: SUCCESS
  results:
    - FAILURE
    - SUCCESS

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #839, Fixes #862
Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/bindings/AbstractBinding.java [hunk 1]
```diff
@@ -1,15 +1,67 @@
...
         }
     }
+
+    protected Value getEvalResultForMap(Value evalResult, LoopStatement loopStatement, String collectionExpression) {
+        if (loopStatement instanceof MapForLoopStatement) {
+            if (evalResult != null && evalResult.get() instanceof Map) {
+                List<Value> entriesAsValues = new ArrayList<>();
+                @SuppressWarnings("unchecked") Set<Map.Entry<Serializable, Serializable>> entrySet = ((Map) evalResult.get()).entrySet();
+                for (Map.Entry<Serializable, Serializable> entry : entrySet) {
+                    entriesAsValues.add(ValueFactory.create(Pair.of(
```
Comment (Bonczidai) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/bindings/AbstractBinding.java]: Y did you added `ValueFactory.create` here? Do we need it?

File: cloudslang-entities/src/main/java/io/cloudslang/lang/entities/ListForLoopStatement.java [hunk 2]
```diff
@@ -25,13 +25,19 @@
 public class ListForLoopStatement extends LoopStatement implements Serializable {
 
     private static final long serialVersionUID = -540865117927676643L;
+    public static final String FOR_LOOP_VAR_NAME_CANNOT_BE_EMPTY = "for loop var name cannot be empty";
```
Comment (gituser173) [inline cloudslang-entities/src/main/java/io/cloudslang/lang/entities/ListForLoopStatement.java]: renamed

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/bindings/AbstractBinding.java (hunk 1 above)
Comment (Bonczidai) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/bindings/AbstractBinding.java]: 👍
