### PR TITLE
When a step has loop and the for statement is empty, it passes CS compilation. Should fail

### LINKED ISSUE #841: When a step has loop and the for statement is empty, it passes CS compilation. Should fail

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #841

Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/TransformersHandler.java [hunk 1]
```diff
@@ -54,8 +54,10 @@ public static String keyToTransform(Transformer transformer) {
                 if (data != null) {
                     transformedData.put(key, (Serializable) data);
                 }
-                for (RuntimeException rex : transformModellingResult.getErrors()) {
-                    errors.add(wrapErrorMessage(rex, errorMessagePrefix));
+                if (rawData.containsKey(key)) {
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/TransformersHandler.java]: hmz

**Comment by Bonczidai** [comment]
👍 please also add a test for `for: ''` case

**Comment by Bonczidai** [comment]
🆒
