### PR TITLE
accumulate missing error

### LINKED ISSUE #707: Incorrect type for post step data items
```console
10:36:09 [ERROR] Exception: Failed creating Slang models for file: '/home/ubuntu/cloud-slang-content/content/io/cloudslang/cloud/openstack/servers/create_server_flow.sl'.
Error transforming source: create_server_flow to a Slang model. For step: update_body_json_with_boot_json - Incorrect type for post step data items.
```

```yaml
- publish:
    - output:
```

execution should fail earlier than the exception we got

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #707 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java [hunk 1]
```diff
@@ -167,7 +167,11 @@ public ExecutableModellingResult transformToExecutable(ParsedSlang parsedSlang,
                 errors.addAll(validateFlowResultsHaveNoExpression(results, execName));
 
                 executableDependencies = fetchDirectStepsDependencies(workflow);
-                systemPropertyDependencies = dependenciesHelper.getSystemPropertiesForFlow(inputs, outputs, results, workflow.getSteps());
+                try {
+                    systemPropertyDependencies = dependenciesHelper.getSystemPropertiesForFlow(inputs, outputs, results, workflow.getSteps());
+                } catch (RuntimeException ex) {
+                    errors.add(ex);
+                }
```
Comment (gituser173) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java]: shouldn't the exception be added to the list also in the case of the OPERATION in this switch?

Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java]: good catch, also adding a test for it
