### PR TITLE
validate result name against on_failure

### LINKED ISSUE #796: Step/Result should not accept name on failure
Step/result cannot be called on-failure

Step: “Below 'on_failure' property there should be a list of steps and not a map” – this error message should be improved
Result: the check does not work

Expected:
No step or response should be called 'on_failure' or any other case combination e.g.: 'ON_Failure', 'ON_FAILURE' etc 
Relevant message should be displayed at compilation

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #796 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/PreCompileValidatorImpl.java [hunk 1]
```diff
@@ -283,6 +283,17 @@ public void validateDefaultResult(List<Result> results, String artifactName, Lis
         }
     }
 
+    @Override
+    public void validateResultName(String resultName) {
+        validateKeywords(resultName);
+    }
+
+    private void validateKeywords(String resultName) {
+        if (SlangTextualKeys.ON_FAILURE_KEY.equalsIgnoreCase(resultName)) {
```
Comment (gituser173) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/PreCompileValidatorImpl.java]: don't we need to validate against more keywords?

**Comment by gituser173** [comment]
Looks good :+1:
