### PR TITLE
Fix listSlangFiles method

### LINKED ISSUE #938: Fix listSlangFiles method
improve efficiency

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #938

Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

File: cloudslang-api-commons/src/main/java/io/cloudslang/lang/commons/services/impl/SlangCompilationServiceImpl.java [hunk 1]
```diff
@@ -84,18 +87,21 @@ public File getFile(final String filePath) {
...
-            if (Extension.SL.equals(Extension.findExtension(file.getName()))) {
-                result.add(file);
-            }
-        }
-        return result;
+        return FileUtils.listFiles(directory,
+                new IOFileFilter() {
+                    @Override
+                    public boolean accept(File file) {
+                        return Extension.SL.equals(Extension.findExtension(file.getName()));
```
Comment (lucian-cm) [inline cloudslang-api-commons/src/main/java/io/cloudslang/lang/commons/services/impl/SlangCompilationServiceImpl.java]: should use == to compare `Extension `enum

File: cloudslang-api-commons/src/test/java/io/cloudslang/lang/commons/services/impl/SlangCompilationServiceImplTest.java [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+        List<String> folders = new ArrayList<>();
+        folders.add(getClass().getResource("/executables").toURI().getPath());
+        slangCompilationService.compileFolders(folders, compilationHelper);
+
+        InOrder inOrderHelper = inOrder(compilationHelper);
+        inOrderHelper.verify(compilationHelper, times(4)).onEveryFile(any(Ansi.Color.class), anyString());
+        inOrderHelper.verify(compilationHelper).onCompilationFinish();
+        inOrderHelper.verifyNoMoreInteractions();
+        InOrder inOrder = inOrder(slang);
+        inOrder.verify(slang, times(4)).compileSource(
```
Comment (lucian-cm) [inline cloudslang-api-commons/src/test/java/io/cloudslang/lang/commons/services/impl/SlangCompilationServiceImplTest.java]: it is a little better to actually have inOrder.verify with normal times(1) and specify the exact `SlangSource` for each such call of `compileSource ` method

**Comment by lucian-cm** [comment]
Merging as comments were fixed.
