### PR TITLE
System tests framework missing functionality

### LINKED ISSUE #177: Add basic missing functionality to the content system tests framework
**Tasks**:
- [x] result
- [x] support test case that expects an exception
- [x] Use the description for printing in the log.info the test case running, and for printing to sys out in case of failure

### PR DESCRIPTION
**Pull request by tudorlesan**
Fixes #177
Signed-off-by: Lesan Tudor <tudor-andrei.lesan@hp.com>

### CODE REVIEW

**Comment by tudorlesan** [comment]
#177

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/SlangTestRunner.java [hunk 1]
```diff
@@ -134,11 +143,30 @@ public Long trigger(String testCaseName, CompilationArtifact compilationArtifact
...
         return executionId;
     }
+
+    private String getResultFromFileName(String fileName) {
+
+        int dashPosition = fileName.lastIndexOf('-');
+        if (dashPosition > 0 && dashPosition < fileName.length()) {
+            return fileName.substring(dashPosition + 1);
+        } else {
+            return "SUCCESS";
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/SlangTestRunner.java]: Use *ScoreLangConstants.SUCCESS_RESULT*

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java [hunk 2]
```diff
@@ -77,6 +77,8 @@ public synchronized void onEvent(ScoreEvent scoreEvent) throws InterruptedExcept
                         data.get(EventConstants.SCORE_ERROR_MSG));
                 break;
             case ScoreLangConstants.SLANG_EXECUTION_EXCEPTION:
+                flowFinished.set(true);
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java]: Eliya just merged Shehab's change that ensures now that when we get to a SLANG_EXECUTION_EXCEPTION event, we will always get also a SCORE_ERROR_EVENT, so you can remove this line now

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java [hunk 3]
```diff
@@ -77,6 +77,8 @@ public synchronized void onEvent(ScoreEvent scoreEvent) throws InterruptedExcept
...
+                result = "FAILURE";
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java]: You shouldn't put here failure result. We can get to a result=FAILURE only in cases where we finished the execution correctly with SCORE_FINISHED_EVENT and not in cases of exceptions.

**Comment by tudorlesan** [comment]
@orius123 @meirwah could you review please?

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java [hunk 4]
```diff
@@ -73,14 +75,16 @@ public synchronized void onEvent(ScoreEvent scoreEvent) throws InterruptedExcept
                 flowFinished.set(true);
                 break;
             case EventConstants.SCORE_ERROR_EVENT :
+            case EventConstants.SCORE_FAILURE_EVENT :
                 errorMessage.set(TEST_CASE_FAILED + testCaseName + ". " + data.get(EventConstants.SCORE_ERROR_LOG_MSG) + " , " +
                         data.get(EventConstants.SCORE_ERROR_MSG));
+                flowFinished.set(true);
+                result = ScoreLangConstants.FAILURE_RESULT;
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java]: Should not assign a result. Need to remove it

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java [hunk 5]
```diff
@@ -121,6 +128,10 @@ public ReturnValues getExecutionReturnValues(){
     private void printFinishEvent(Map<String, Serializable> data) {
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java]: I think that this method should be removed from here. You can print the log in the testRunner. The event listener is not the right location for it. 
This way you can also remove the expectedResult variable

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java [hunk 6]
```diff
@@ -50,11 +50,13 @@
     private AtomicBoolean flowFinished = new AtomicBoolean(false);
     private AtomicReference<String> errorMessage = new AtomicReference<>("");
     private String testCaseName;
+    private String expectedResult;
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/TriggerTestCaseEventListener.java]: You can remove this new memebr. Look at the comment below

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/SlangTestRunner.java [hunk 7]
```diff
@@ -134,11 +156,28 @@ public Long trigger(String testCaseName, CompilationArtifact compilationArtifact
         String executionResult = executionReturnValues.getResult();
 
         String errorMessageFlowExecution = testsEventListener.getErrorMessage();
-        if (StringUtils.isNotEmpty(errorMessageFlowExecution) || !executionResult.equals(result)) {
-            // exception occurred during flow execution
-            throw new RuntimeException(errorMessageFlowExecution);
+
```
Comment (oritstone) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/tester/SlangTestRunner.java]: You can add here the logging of the status of the tests, instead of the printing method in the event listener
