### PR TITLE
Inputs initialized with null before binding

### LINKED ISSUE #620: Inputs initialized with null before binding
the inputs / arguments binding initializes the input name with null before binding:

after ` - input1: ${ input1 }` will have null value after binding instead of an exception
IMHO this case is no longer valid and it should throw an exception.
For this case we have `- input1` syntax and the `get` function

### PR DESCRIPTION
**Pull request by gituser173**
Fixes  #620
Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

File: cloudslang-entities/src/main/java/io/cloudslang/lang/entities/bindings/Input.java [hunk 1]
```diff
@@ -110,10 +117,16 @@ public InputBuilder(String name, Serializable value) {
 			encrypted = false;
 			required = true;
 			privateInput = false;
+            defaultSpecified = false;
```
Comment (Bonczidai) [inline cloudslang-entities/src/main/java/io/cloudslang/lang/entities/bindings/Input.java]: pay attention to indent :)

**Comment by Bonczidai** [comment]
:+1: looks cool - please also add a system test

```
    - null_input:
        default: ${null_input}
        required: false
```

which is supposed to fail

**Comment by Bonczidai** [comment]
please also merge from master (sensitive + versioning)

File: cloudslang-entities/src/main/java/io/cloudslang/lang/entities/bindings/Input.java [hunk 2]
```diff
@@ -29,6 +29,7 @@
 
 	private boolean required;
 	private boolean privateInput;
+    private boolean defaultSpecified;
```
Comment (Bonczidai) [inline cloudslang-entities/src/main/java/io/cloudslang/lang/entities/bindings/Input.java]: do you still need this property after the changes?

**Comment by Bonczidai** [comment]
please only assign once build passes : )

**Comment by Bonczidai** [comment]
:+1: we'll merge it after sensitive data + versioning fixes are in
