### PR TITLE
enforce flow name

### LINKED ISSUE #489: Enforce flow name and file name to be identical
*fail compilation* if flow name and file name are different.
(doing it through the CLI)

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #489 
Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
please check why the build fails

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompilerImpl.java [hunk 1]
```diff
@@ -65,10 +65,28 @@ public Executable preCompile(SlangSource source) {
...
         Validate.notEmpty(executable.getNamespace(),"Operation/Flow " +executable.getName() +" must have a namespace");
+        ValidateFileName(source, parsedSlang);
 
         return executable;
     }
 
+    private void ValidateFileName(SlangSource source, ParsedSlang parsedSlang) {
+        String fileName = source.getName().substring(0, source.getName().lastIndexOf("."));
+        String flowOrOperationName = getFlowOrOperationName(parsedSlang);
+        Validate.isTrue(fileName.equals(flowOrOperationName),
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompilerImpl.java]: you should move the validation logic in SlangModellerImpl.transformToExecutable() where you already have the necessary data: ParsedSlang.getnName() and exeutableName

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompilerImpl.java [hunk 2]
```diff
@@ -65,10 +65,28 @@ public Executable preCompile(SlangSource source) {
         // Then we transform the parsed Slang source to a Slang model
         Executable executable = slangModeller.createModel(parsedSlang);
         Validate.notEmpty(executable.getNamespace(),"Operation/Flow " +executable.getName() +" must have a namespace");
+        ValidateFileName(source, parsedSlang);
 
         return executable;
     }
 
+    private void ValidateFileName(SlangSource source, ParsedSlang parsedSlang) {
+        String fileName = source.getName().substring(0, source.getName().lastIndexOf("."));
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompilerImpl.java]: IMHO you should do some checks here to make sure things don;t go wrong - e.g. in case the file name does not contain `.` wouldn;t we get an exception?

**Comment by Bonczidai** [comment]
please add test cases: flow name without extension, flow name with `.sl.yaml` extension

**Comment by Bonczidai** [comment]
related to #575

**Comment by Bonczidai** [comment]
@gituser173 me really it :+1: 

couple of things that are leftover:
- deal with SLANG_FILE_EXTENSIONS in SlangContentVerifier
- deal with PROPERTIES_FILE_EXTENSIONS in SlangBuilder
- methods that use these consts can be enhanced with Extension.findExtension() method in CompielrHelperImpl, TestCasesYamlParser, SlangContentVerifier (extensisbility enhancement for new extensions)
- "optional"  - all over the code e.g. SlangModeller - line 67 - use enum values
- post screenshot on how the error message looks in CLI

**Comment by gituser173** [comment]
capture

**Comment by Bonczidai** [comment]
missing `.` in the message

**Comment by gituser173** [comment]
thanks

**Comment by gituser173** [comment]
capture

**Comment by gituser173** [comment]
@Bonczidai removed the newline

**Comment by Bonczidai** [comment]
:100:
