### PR TITLE
Fix duplicate check for same source, Value conversion in CLI

### LINKED ISSUE #781: CLI doesn't accept flow inputs from command line
cslang>run --f C:/training/versioning-training/cp/target/slang-versioning-cp-1.0
.0/Content/Library/versioning_flows/versioning/py_flow.sl --cp C:/training/versi
oning-training/cp/target/slang-versioning-cp-1.0.0/Content/Library/versioning_fl
ows/operations --i var1='1',var2='2',var3='3'
Command failed java.lang.RuntimeException: Slang Error: Error running: 'py_flow'
.
     Error binding input: 'var1',
    Error is: java.lang.String cannot be cast to io.cloudslang.lang.entities.bin
dings.values.Value

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #781 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java [hunk 1]
```diff
@@ -59,11 +59,13 @@ private boolean navigationListContainsKey(List<Map<String, String>> stepNavigati
 
     @Override
     public void validateNoDuplicateExecutablesBasedOnFQN(
```
Comment (gituser173) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java]: maybe rename to validateNoDuplicateExecutables

File: cloudslang-compiler/src/test/java/io/cloudslang/lang/compiler/CompileDependenciesTest.java [hunk 2]
```diff
@@ -155,4 +155,19 @@ public void circularDependencies() throws Exception {
...
+        URI flow = getClass().getResource("/basic_flow.yaml").toURI();
+        URI importedOperation = getClass().getResource("/test_op.sl").toURI();
+        Set<SlangSource> path = new HashSet<>();
+        path.add(SlangSource.fromFile(importedOperation));
+        SlangSource flowSource = SlangSource.fromFile(flow);
+        path.add(flowSource);
+
+        Assert.assertTrue(path.contains(flowSource));
+        CompilationArtifact compilationArtifact = compiler.compile(flowSource, path);
+        Assert.assertNotNull(compilationArtifact);
```
Comment (gituser173) [inline cloudslang-compiler/src/test/java/io/cloudslang/lang/compiler/CompileDependenciesTest.java]: maybe add some asserts here
