### PR TITLE
Parsing metadata fails all together

### LINKED ISSUE #960: Parsing metadata fails all together
When processing the description of a flow, the parsing is stops immediately, therefor it's not possible to extract the valid elements.

E.g. having a bad flow input name

`#! @input flow_input_#2: description - details`

prevents extracting the description of the other inputs.

A more relaxed parsing approach, instead of the "all or nothing", would provide more flexibility.

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #960

Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

**Comment by Bonczidai** [comment]
@gituser173 is this PR still in progress or ready for review?

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/validation/StaticValidatorImpl.java [hunk 1]
```diff
@@ -33,64 +33,80 @@
...
         String fileNameNoExtension = Extension.removeExtension(slangFile.getName());
         String executableNameErrorMessage = "Error validating Slang file: \'" + slangFile.getAbsoluteFile() +
                 "\'. Name of flow or operation: \'" + executable.getName() +
                 "\' is not valid.\nIt should be identical to the file name: \'" + fileNameNoExtension + "\'";
-        Validate.isTrue(fileNameNoExtension.equals(executable.getName()), executableNameErrorMessage);
+        addExceptionIfTrue(fileNameNoExtension.equals(executable.getName()), executableNameErrorMessage, exceptions);
+    }
+
+    public void addExceptionIfEmptyString(String string, String message, Queue<RuntimeException> exceptions) {
+        if (string == null || string.length() == 0) {
```
Comment (Bonczidai) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/validation/StaticValidatorImpl.java]: StringUtils.isEmpty?

File: cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/verifier/CompileResult.java [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+
+import java.util.ArrayDeque;
+import java.util.HashMap;
+import java.util.Map;
+import java.util.Queue;
+
+public class CompileResult {
+
+    private Map<String, CompilationArtifact> results;
+    private Queue<RuntimeException> exceptions;
```
Comment (Bonczidai) [inline cloudslang-content-verifier/src/main/java/io/cloudslang/lang/tools/build/verifier/CompileResult.java]: hmm, any specific reason to use queue here instead of a list?

**Comment by Bonczidai** [comment]
@tethryus you can also take a look if interested
