### PR TITLE
resolve python serialization message bug

### LINKED ISSUE #464: CLI wrong error message: non-serializable python context [1]
null_message

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #464 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

**Comment by Bonczidai** [comment]
cool_message

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/ActionSteps.java [hunk 1]
```diff
@@ -240,19 +231,23 @@ private void handleSerializableSessionContextArgument(Map<String, SerializableSe
...
 
     //we need this method to be synchronized so we will not have multiple scripts run in parallel on the same context
-    private synchronized Map<String, Serializable> runPythonAction(Map<String, Serializable> callArguments,
-                                                             String script) {
+    private synchronized Map<String, Serializable> runPythonAction(
+            Map<String, Serializable> callArguments,
+            String script,
+            String operationName) {
 
+        cleanInterpreter(interpreter);
```
Comment (Bonczidai) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/ActionSteps.java]: changed `cleanInterpreter` location because of this situation:

execute a script that fails on not serializable variable issue -- you can not execute another valid script after since variable remained in the context
