### PR TITLE
Compiler error handling

### LINKED ISSUE #564: Be able to extract language data from flows that may be incorrect but valid Yaml
When creating new flow the workflow is empty.
When trying to compile this flow in order to get the namespace, for example, we get an error that our workflow is empty.
Can we make such scenarios legal in compiler?

thank

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #564 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java [hunk 1]
```diff
@@ -91,19 +103,33 @@ public void initScopedTransformersAndKeys() {
         return filter(having(on(Transformer.class).getScopes().contains(scope)), transformers);
     }
 
-    public Executable transformToExecutable(ParsedSlang parsedSlang, String execName, Map<String, Object> executableRawData) {
+    @SuppressWarnings("unchecked")
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java]: I am not much of a fan of `SupressWarnings` on methods..

can we use some tricks? like:
```java
@SuppressWarnings("unchecked")
List<Map<String, Map<String, Object>>> onFailureDataHelper = (List<Map<String, Map<String, Object>>>)taskData.values().iterator().next();
onFailureData = onFailureDataHelper;
```

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java [hunk 2]
```diff
@@ -272,45 +308,53 @@ private Workflow compileWorkFlow(List<Map<String, Map<String, Object>>> workFlow
...
-        transformersHandler.validateKeyWords(taskName, taskRawData, ListUtils.union(preTaskTransformers, postTaskTransformers), TaskAdditionalKeyWords, null);
+        errors.addAll(transformersHandler.checkKeyWords(taskName, taskRawData, ListUtils.union(preTaskTransformers, postTaskTransformers), TaskAdditionalKeyWords, null));
 
-        try {
-            preTaskData.putAll(transformersHandler.runTransformers(taskRawData, preTaskTransformers));
-            postTaskData.putAll(transformersHandler.runTransformers(taskRawData, postTaskTransformers));
-        } catch (Exception ex){
-            throw new RuntimeException("For task: " + taskName + " syntax is illegal.\n" + ex.getMessage(), ex);
-        }
+        String errorMessagePrefix = "For task: " + taskName + " syntax is illegal.\n";
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java]: I see that you specify a prefix for tasks but you don't do that for executable and action - Y?

**Comment by Bonczidai** [comment]
@ifatgv / @ifatgv4 this looks :100: 

please add lots of test cases to make sure we don't miss anything

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompiler.java [hunk 3]
```diff
@@ -27,10 +28,19 @@
...
      * Pre-compile a CloudSlang source into an {@link io.cloudslang.lang.compiler.modeller.model.Executable}
      * @param source the {@link SlangSource}
-     * @return an {@link io.cloudslang.lang.compiler.modeller.model.Executable} object, containing either a flow or operation in the file.
+     * @return an {@link io.cloudslang.lang.compiler.modeller.model.Executable} object, containing either a flow or
+     * operation in the file.
      */
     Executable preCompile(SlangSource source);
 
+    /**
+     * Pre-compile a CloudSlang source into an {@link ExecutableModellingResult}
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompiler.java]: I think we should mention in the javadoc that this version will collect the exceptions instead of failing

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java (hunk 1 above)
Comment (ifatgv4) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java]: Done

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java (hunk 2 above)
Comment (ifatgv4) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/modeller/ExecutableBuilder.java]: I tried to keep the error messages as is. Only task errors had a prefix, so I only added it to them.
However, there is no reason not to add such a prefix.
I added one for action and executable

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompiler.java (hunk 3 above)
Comment (ifatgv4) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompiler.java]: Done
