### PR TITLE
validate navigation section against dependency results

### LINKED ISSUE #808: Validate step declares exact dependency results in navigation section
missing navigation in step means that it has default behavior.
in case the original step results does not contain failure and success (only the two of them) we want the compilation to fail.

### PR DESCRIPTION
**Pull request by Bonczidai**
Fixes #808 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java [hunk 1]
```diff
@@ -138,28 +133,73 @@ private boolean isForLoop(Step step, List<String> breakValuesList) {
...
+            ));
+        }
+    }
+
+    private String getErrorMessagePrefix(Flow flow, Step step) {
+        return "Cannot compile flow '" + flow.getName() +
+                "' since for step '" + step.getName() + "'";
+    }
+
+    private List<String> mapMapToKey(List<Map<String, String>> collection) {
```
Comment (gituser173) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java]: maybe rename to "getKeyList" or something better

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java [hunk 2]
```diff
@@ -138,28 +133,73 @@ private boolean isForLoop(Step step, List<String> breakValuesList) {
...
+        List<String> result = new ArrayList<>();
+        for (Map<String, String> element : collection) {
+            result.add(element.keySet().iterator().next());
+        }
+        return result;
+    }
+
+    private List<String> mapResultsToNames(List<Result> results) {
```
Comment (gituser173) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java]: "getResultsNamesList"? WDYT?

**Comment by gituser173** [comment]
Looks good :+1:

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java (hunk 1 above)
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java]: alright

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java (hunk 2 above)
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/CompileValidatorImpl.java]: that's also perfectly valid - but this method is actually a clear lambda expression (in python it would be ~ `map(lambda x : x['name'], results))`, so I would like to stay with this naming (it will be easier to spot when we move to Java 8)

**Comment by Bonczidai** [comment]
@gituser173 thanks for the review, merging
