### PR TITLE
System properties are not retrived in case duplicate ids 

### LINKED ISSUE #848: System properties are not retrived in case duplicate ids
Currently, when a SP file has any error, like duplicate identifier, the precompile does not retrieve the SPs inside.
This mean that in WS if I have a file SP1 with two identifiers SP1.a and SP1.a and I create in a new file SP2 with SP1.a identifier I will not get it as duplicate.

I think SP precompile should behave like a flow and return the content of the file.

Possible solution:

We can separate the layers like we do with precompile: preCompileSource -> model (what we could extract) + exceptions; precompile -> model or throw first exception,
We can do something similar for SPs

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #848
Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompilerImpl.java [hunk 1]
```diff
@@ -116,105 +117,130 @@ public ExecutableModellingResult preCompileSource(SlangSource source) {
...
+        }
+        return systemPropertyModellingResult.getSystemProperties();
+    }
+
+    @Override
+    public SystemPropertyModellingResult loadSystemPropertiesFromSource(SlangSource source) {
+        ParseModellingResult parseModellingResult = parseSystemPropertiesFile(source);
+        SystemPropertyModellingResult systemPropertyModellingResult =
+                extractProperties(parseModellingResult.getParsedSlang(), source);
+        systemPropertyModellingResult.getErrors().addAll(parseModellingResult.getErrors());
```
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/SlangCompilerImpl.java]: I'd put the parse errors before the extract properties errors

File: cloudslang-compiler/src/test/java/io/cloudslang/lang/compiler/LoadSystemPropertiesTest.java [hunk 2]
```diff
@@ -183,6 +210,19 @@ public void testInvalidCharsNamespace() throws Exception {
     }
 
     @Test
+    public void testInvalidCharsNamespaceFromSource() throws Exception {
```
Comment (Bonczidai) [inline cloudslang-compiler/src/test/java/io/cloudslang/lang/compiler/LoadSystemPropertiesTest.java]: IMHO you should validate that you get all the exceptions when having multiple ones

**Comment by Bonczidai** [comment]
👍 take a look on the comments
