### PR TITLE
Fix cli log: missing call arguments for python action

### LINKED ISSUE #331: CLI log: Missing CALL_ARGUMENTS for Python action [1]
Observed the following in CLI log:

Java action - call arguments logged:
```
STEP_TYPE=ACTION, STEP_NAME=null, TYPE=EVENT_ACTION_START, CALL_ARGUMENTS={characterSet=UTF-8, agentForwarding=null, command=docker ps -a, timeout=600000, password=null, pty=false, privateKeyFile=c:/.../id_rsa, port=22, host=111.111.111.111, arguments=null, closeSession=false, username=core}
```

Python action - call arguments not logged:
```
STEP_TYPE=ACTION, STEP_NAME=null, TYPE=EVENT_ACTION_START, CALL_ARGUMENTS={}
```

however there are inputs declared in the operation.

Shouldn't call arguments appear in the log also for Python actions (EVENT_ACTION_START events)?

### PR DESCRIPTION
**Pull request by maayan-avraham**
Fixes #331
Signed-off-by: Maayan Avraham <maayan.avraham@hpe.com>

### CODE REVIEW

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/ActionSteps.java [hunk 1]
```diff
@@ -63,10 +60,16 @@ public void doAction(@Param(ScoreLangConstants.RUN_ENV) RunEnvironment runEnv,
 
         Map<String, Serializable> returnValue = new HashMap<>();
         Map<String, Serializable> callArguments = runEnv.removeCallArguments();
+        Map<String, Serializable> callArgumentsDeepCopy = new HashMap<>();
+
+        for (Map.Entry<String, Serializable> entry : callArguments.entrySet()) {
+            callArgumentsDeepCopy.put(new String(entry.getKey().toString()),  SerializationUtils.clone(entry.getValue()));
```
Comment (Bonczidai) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/ActionSteps.java]: you can use simply `entry.getKey()` here instead of `new String(entry.getKey().toString()` because of diamond operator (`Map.Entry<String, Serializable> entry`)

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/ActionSteps.java [hunk 2]
```diff
@@ -313,4 +316,6 @@ private void executePythonScript(PythonInterpreter interpreter, String script, M
     private void cleanInterpreter(PythonInterpreter interpreter) {
         interpreter.setLocals(new PyStringMap());
     }
+
+
```
Comment (Bonczidai) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/ActionSteps.java]: how about only one newline?

File: cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java [hunk 3]
```diff
@@ -135,6 +136,75 @@ public void doJavaActionWrongClassTest() {
...
+        Collection<ScoreEvent> events = runtimeServices.getEvents();
+
+        Assert.assertFalse(events.isEmpty());
+        ScoreEvent eventActionStart = null;
+        for(ScoreEvent event:events){
+            if(event.getEventType().equals(ScoreLangConstants.EVENT_ACTION_START)){
+                eventActionStart = event;
+            }
+        }
+        assert eventActionStart != null;
```
Comment (Bonczidai) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: I am not much of an `assert` fan in unit tests -- I think you should use `assertNotNull` instead

File: cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java [hunk 4]
```diff
@@ -135,6 +136,75 @@ public void doJavaActionWrongClassTest() {
...
+        //invoke doAction
+        actionSteps.doAction(runEnv,new HashMap<String, Object>(), PYTHON, "", "", runtimeServices, userPythonScript, 2L, "operationName");
+
+        Collection<ScoreEvent> events = runtimeServices.getEvents();
+
+        Assert.assertFalse(events.isEmpty());
+        ScoreEvent eventActionStart = null;
+        for(ScoreEvent event:events){
+            if(event.getEventType().equals(ScoreLangConstants.EVENT_ACTION_START)){
+                eventActionStart = event;
```
Comment (Bonczidai) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: with this logic you verify that the event was fired at least once, maybe you should check that it was fired exactly once

File: cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java [hunk 5]
```diff
@@ -135,6 +136,75 @@ public void doJavaActionWrongClassTest() {
...
+            }
+        }
+        assert eventActionStart != null;
+        Map<String, Serializable> data = (HashMap)eventActionStart.getData();
+        for (Map.Entry<String, Serializable> entry : data.entrySet()) {
```
Comment (Bonczidai) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: how I would refactor this section (e.g. no need for `for`):

- cast `.getData()` to `LanguageEventData`
- update `LanguageEventData` with getter / setter for `CALL_ARGUMENT` const
- use this getter to retrieve the call args
- verify call args content is equal to your inputs (`callArguments.put("index", 1);`)
- don't `return` and `Assert.fail();` you can simply use `assertEquals("message", expected, actual)`

File: cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java [hunk 6]
```diff
@@ -135,6 +136,75 @@ public void doJavaActionWrongClassTest() {
...
+            if (entry.getKey().equals("CALL_ARGUMENTS")){
+                Assert.assertNotNull(entry.getValue());
+                return;
+            }
+        }
+        Assert.fail();
+    }
+
+    @Test
+    public void doActionJavaActionCheckCallArgumentsOnEvent() {
```
Comment (Bonczidai) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: same comments apply as in python method case

**Comment by Bonczidai** [comment]
really nice fix - me like it

File: cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java (hunk 4 above)
Comment (maayan-avraham) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: @Bonczidai This test is only for checking that the call arguments are correct, so why should I verify here that the event fired exactly once?

Comment (Bonczidai) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: ok -- how about adding a `break` so we will not iterate over the remaining part of the collection?

Comment (maayan-avraham) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/steps/ActionStepsTest.java]: I agree with you, thanks

**Comment by maayan-avraham** [comment]
@Bonczidai  it's ready for merge
