### PR TITLE
Path redo

### LINKED ISSUE #300: wrong path created by slang actions
the path created by slang action is not correct and also doe not represent the language syntax and how does the user expect to.

comment: i already have the fix

### PR DESCRIPTION
**Pull request by orius123**
fixes #300

### CODE REVIEW

**Comment by orius123** [comment]
@oritstone please review and we will merge this one

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/AsyncLoopSteps.java [hunk 1]
```diff
@@ -95,20 +90,15 @@ public void addBranches(@Param(ScoreLangConstants.ASYNC_LOOP_STATEMENT_KEY) Asyn
...
-                        runEnv.getExecutionPath().getCurrentPathPeekForward(),
-                        Pair.of(ScoreLangConstants.REF_ID, refId),
-                        Pair.of(RuntimeConstants.SPLIT_ITEM_KEY, splitItem),
-                        Pair.of(LanguageEventData.levelName.TASK_NAME.name(), nodeName));
+                fireEvent(executionRuntimeServices, ScoreLangConstants.EVENT_BRANCH_START,
+                        "async loop branch created", runEnv.getExecutionPath().getCurrentPath(),
+                        LanguageEventData.StepType.TASK, nodeName, Pair.of(ScoreLangConstants.REF_ID, refId),
+                        Pair.of(RuntimeConstants.SPLIT_ITEM_KEY, splitItem));
+
+                runEnv.getExecutionPath().forward();
```
Comment (oritstone) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/AsyncLoopSteps.java]: In the last branch, is it a problem that the path changes? Is there any chance that it will be used somewhere?

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/events/LanguageEventData.java [hunk 2]
```diff
@@ -1,118 +1,127 @@
...
+    }
 
-	public void setOutputs(Map<String, Serializable> outputs) {
-		put(OUTPUTS, (Serializable)outputs);
-	}
+    public Map<String, Serializable> getInputs() {
+        return (Map<String, Serializable>) get(BOUND_INPUTS);
+    }
 
-    public List<Serializable> getAsyncLoopBoundExpression() {
```
Comment (oritstone) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/events/LanguageEventData.java]: Undelete these 2 methods

File: cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/events/LanguageEventDataTest.java [hunk 3]
```diff
@@ -149,15 +147,4 @@ public void testOutputs() {
 		assertEquals(outputs, eventData.get(LanguageEventData.OUTPUTS));
 	}
 
-    /**
-     * Test method for {@link LanguageEventData#getAsyncLoopBoundExpression()}.
-     */
-    @Test
-    public void testAsyncLoopBoundExpression() {
```
Comment (oritstone) [inline cloudslang-runtime/src/test/java/io/cloudslang/lang/runtime/events/LanguageEventDataTest.java]: un-delete the test

**Comment by oritstone** [comment]
@orius123 fix issues and merge

File: cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/AsyncLoopSteps.java (hunk 1 above)
Comment (orius123) [inline cloudslang-runtime/src/main/java/io/cloudslang/lang/runtime/steps/AsyncLoopSteps.java]: only if it has another branch after it.
