### PR TITLE
Handle unreachable step, on_failure and result sections

### LINKED ISSUE #778: Unreachable step\result are not handled in CS
Create a flow which has a step\result that are not reachable
See that the flow is valid, such flow should be invalid

### LINKED ISSUE #790: Step and result with same name should fail compilation

### PR DESCRIPTION
**Pull request by Bonczidai**
fixes #778 
fixes #790 

Signed-off-by: Bonczidai Levente <levente.bonczidai@hpe.com>

### CODE REVIEW

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/PreCompileValidatorImpl.java [hunk 1]
```diff
@@ -238,37 +238,108 @@ private void validateFlow(Flow compiledFlow, ExecutableModellingResult result) {
...
+            List<RuntimeException> stepErrors = new ArrayList<>();
+            List<RuntimeException> resultsErrors = new ArrayList<>();
+
+            validateNavigation(
+                    compiledFlow.getWorkflow().getSteps().getFirst(),
+                    steps,
+                    resultNames,
+                    reachableStepNames,
+                    reachableResultNames,
+                    navigationErrors
```
Comment (gituser173) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/PreCompileValidatorImpl.java]: maybe you could put here `result.getErrors()` instead of navigationErrors, same thing for stepErrors and resultsErrors

**Comment by gituser173** [comment]
:+1:

File: cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/PreCompileValidatorImpl.java (hunk 1 above)
Comment (Bonczidai) [inline cloudslang-compiler/src/main/java/io/cloudslang/lang/compiler/validator/PreCompileValidatorImpl.java]: :+1:
