### PR TITLE
Downloading artifact message

### LINKED ISSUE #846: CLI display message when starting/finished to download dependencies
A nice feature, would be having a message that informs you that the CLI has started downloading the required dependencies and a SUCCESS or FAILURE message in case something goes wrong while downloading them.  It does not have to show the full message, with all the dependencies that are downloading, just something like "Download Maven dependencies, please wait ..." and after it finishes "Maven dependencies downloaded successfully". A Failure message appears, in case of a failure in downloading them.

### PR DESCRIPTION
**Pull request by gituser173**
Fixes #846
Requires https://github.com/CloudSlang/score/pull/132

Signed-off-by: Claudiu Ban claudiu-laurian.ban@hpe.com

### CODE REVIEW

**Comment by lucian-cm** [comment]
@gituser173 lgtm :)
Please add a test for this and this can be merged

File: cloudslang-cli/src/main/java/io/cloudslang/lang/cli/services/SyncTriggerEventListener.java [hunk 1]
```diff
@@ -126,6 +123,14 @@ else if (data.containsKey(LanguageEventData.OUTPUTS) && data.containsKey(Languag
                 flowFinished.set(true);
                 printFinishEvent(data);
                 break;
+            case ScoreLangConstants.MAVEN_DEPENDENCY_BUILD:
+                consolePrinter.printWithColor(Ansi.Color.CYAN,
```
Comment (lucian-cm) [inline cloudslang-cli/src/main/java/io/cloudslang/lang/cli/services/SyncTriggerEventListener.java]: static import for Ansi.Color.CYAN makes it a little more readable

Comment (lucian-cm) [inline cloudslang-cli/src/main/java/io/cloudslang/lang/cli/services/SyncTriggerEventListener.java]: seems you can extract a two line method for the two newly added cases since the processing is identical

File: cloudslang-entities/src/main/java/io/cloudslang/lang/entities/ScoreLangConstants.java [hunk 2]
```diff
@@ -39,6 +39,9 @@
     String PYTHON_ACTION_SCRIPT_KEY = "script";
     String PYTHON_ACTION_DEPENDENCIES_KEY = "dependencies";
 
+    String MAVEN_DEPENDENCY_BUILD = "mavenDependencyBuild";
```
Comment (Bonczidai) [inline cloudslang-entities/src/main/java/io/cloudslang/lang/entities/ScoreLangConstants.java]: Y not reuse from engine?

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by Bonczidai** [comment]
please add a screenshot on how it looks like in CLI

**Comment by gituser173** [comment]
capture

**Comment by gituser173** [comment]
A new release for score is needed for the build to pass

File: cloudslang-cli/src/main/java/io/cloudslang/lang/cli/services/SyncTriggerEventListener.java [hunk 3]
```diff
@@ -15,35 +15,37 @@
 import io.cloudslang.score.events.EventConstants;
 import io.cloudslang.score.events.ScoreEvent;
 import io.cloudslang.score.events.ScoreEventListener;
```
Comment (Bonczidai) [inline cloudslang-cli/src/main/java/io/cloudslang/lang/cli/services/SyncTriggerEventListener.java]: please add a unit test - when events are fired, print is invoked

Comment (gituser173) [inline cloudslang-cli/src/main/java/io/cloudslang/lang/cli/services/SyncTriggerEventListener.java]: added unit test

**Comment by gituser173** [comment]
@Bonczidai revalidated, all good 👍

**Comment by Bonczidai** [comment]
👌 great - let's wait for the new score release

**Comment by Bonczidai** [comment]
@gituser173 score v 0.3.40 is released, please update the PR

**Comment by Bonczidai** [comment]
@gituser173 please also resolve conflicting files

**Comment by gituser173** [comment]
@Bonczidai resolved conflicts, please review

**Comment by Bonczidai** [comment]
great work 👍 merging
